### PR TITLE
Fix parsing when zone index contains uppercase letters

### LINKED ISSUE #82: Zone indexes lost if containing uppercase letters
Zone indexes lost if containing uppercase letters.

Example tests that fail:

```coffee
test.equal( ipaddr.parse('2001:db8:f53a::1%WAT').toString(), '2001:db8:f53a::1%WAT' )
# => Currently returns '2001:db8:f53a::1'

test.equal( ipaddr.parse('2001:db8:f53a::1%sUp').toString(), '2001:db8:f53a::1%sUp' )
# => Currently returns '2001:db8:f53a::1%s'
```

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #82

### CODE REVIEW

**Comment by JamesMGreene** [comment]
When merged, please publish a `1.5.2` release. Thanks!

File: src/ipaddr.coffee [hunk 1]
```diff
@@ -381,7 +381,7 @@ expandIPv6 = (string, parts) ->
     return null
 
   # Remove zone index and save it for later
-  zoneId = (string.match(zoneIndex) || [])[0]
+  zoneId = (string.match(ipv6Regexes['zoneIndex']) || [])[0]
```
Comment (whitequark) [inline src/ipaddr.coffee]: Why even have the `zoneIndex` variable? Just put the entire regexp into `ipv6Regexes`.

Comment (JamesMGreene) [inline src/ipaddr.coffee]: So `zoneIndex` has always been a string:

```coffee
zoneIndex = "%[0-9a-z]{1,}"
```

That was then referenced by multiple other RegExp definitions:

```coffee
ipv6Regexes =
   zoneIndex:    new RegExp zoneIndex, 'i'
   native:       new RegExp "^(::)?(#{ipv6Part})?([0-9a-f]+)?(::)?(#{zoneIndex})?$", 'i'
   transitional: new RegExp "^((?:#{ipv6Part})|(?:::)(?:#{ipv6Part})?)" +
                            "#{ipv4Part}\\.#{ipv4Part}\\.#{ipv4Part}\\.#{ipv4Part}" +
                            "(#{zoneIndex})?$", 'i'
```

The trouble is that this particular changed line (Line 384) was accidentally incorrectly using the string `zoneIndex` rather than the RegExp `ipv6Regexes['zoneIndex']` as it was clearly intending to.

The funny part is that it was accidentally working in most cases because of the strange defaulting behavior of `String.prototype.match`: while it expects 1 RegExp parameter, it will [implicitly handle a non-RegExp argument by wrapping it with the `RegExp` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#A_non-RegExp_object_as_the_parameter). In our case, that means it was working like `new RegExp zoneIndex` instead of the intended `new RegExp zoneIndex, 'i'`.

Comment (whitequark) [inline src/ipaddr.coffee]: Ah nevermind I misread. Sorry.

Comment (JamesMGreene) [inline src/ipaddr.coffee]: No worries, it took me a while to figure out how it was working in the first place for the other cases. 😝

**Comment by JamesMGreene** [comment]
Reminder: please publish a `1.5.2` release with this. Thanks! 💝
